### ISSUE TITLE
Invalid value in unit mcx_host.cpp:315 when trying to run using OpenCL on Linux

### ISSUE THREAD

**Issue by nicocarbone** [fangq/mcxcl#44] opened 2023-05-17 14:43 UTC
I am trying to run the examples of mcxcl and in all of them I get the following error:

```
sh run_benchmark1.sh
MCXCL ERROR(30):Invalid value in unit mcx_host.cpp:315
```

I am running on a AMD GPU in Ubuntu 23.04 using the RustiCL OpenCL driver.

**Comment by fangq** [comment] 2023-05-17 15:01
@nicocarbone, I transferred this issue from mcx to mcxcl - since this is mcxcl specific.

we first need to understand which part is responsible for this error - hardware? driver? opencl runtime? or mcxcl?

can you run `clinfo` and `mcxcl -L` and see if you can list any opencl devices? if not, that means your opencl runtime or ICD was not installed properly.

**Closed** 2023-05-17 16:41 UTC

**Comment by fangq** [comment] 2023-05-17 16:50
should be fixed in the above commit. download from this folder when the CI is complete, then test it on your system

http://mcx.space/nightly/github/

the issue is because your were using an open source AMD opencl runtime, which does not implement AMD extensions such as `CL_DEVICE_GFXIP_MAJOR_AMD`  and `CL_DEVICE_GFXIP_MINOR_AMD`, see this section

https://registry.khronos.org/OpenCL/extensions/amd/cl_amd_device_attribute_query.txt


in a way, this is not a bug of mcxcl, but one for RustiCL.

I am not certain that this runtime can get the desired speed on AMD GPU, so please test it. often times the OEM OpenCL runtime gives the best speed, if not substantially better.

**Comment by nicocarbone** [comment] 2023-05-17 16:58
Great. Thank you!
Indeed, my intent is to test the speed of the open driver. I understand it may be underwhelming.

**Comment by nicocarbone** [comment] 2023-05-18 14:46
I tried the new commit. I had to compile from source as the files from the provided web weren't updated.

It runs, but incorrectly. The benchamark1 returns a nan in the absorbed photons.

> ./run_benchmark1.sh
> ==============================================================================
> =                       Monte Carlo eXtreme (MCX) -- OpenCL                  =
> =          Copyright (c) 2010-2022 Qianqian Fang <q.fang at neu.edu>         =
> =                             http://mcx.space/                              =
> =                                                                            =
> = Computational Optics&Translational Imaging (COTI) Lab - http://fanglab.org =
> =   Department of Bioengineering, Northeastern University, Boston, MA, USA   =
> ==============================================================================
> =    The MCX Project is funded by the NIH/NIGMS under grant R01-GM114365     =
> ==============================================================================
> $Rev::4fdc45$v2022.10$Date::2018-03-29 00:35:53 -04$by $Author::Qianqian Fang$
> ==============================================================================
> - variant name: [Detective MCXCL] compiled with OpenCL version [1]
> - compiled with: [RNG] xoroshiro128+ [Seed Length] 4
> initializing streams ...	init complete : 0 ms
> building kernel with option: -cl-mad-enable -DMCX_USE_NATIVE -DMCX_SRC_PENCIL -DMED_TYPE=1  -DUSE_ATOMIC -DMCX_SAVE_DETECTORS  -DINTERNAL_SOURCE
> build program complete : 30 ms
> - [device 0(1852139309): AMD Radeon Graphics (renoir, LLVM 15.0.7, DRM 3.52, 6.3.1-060301-gen] threadph=5580 extra=6400 np=100000000 nthread=17920 nblock=64 sharedbuf=1536
> set kernel arguments complete : 34 ms
> lauching mcx_main_loop for time window [0.0ns 5.0ns] ...
> simulation run# 1 ... 
> kernel complete:  	10099 ms
> retrieving flux ... 	detected 13687 photons, total: 13687	transfer complete:        10131 ms
> normalizing raw data ...	source 1, normalization factor alpha=inf
> saving data to file ... 216000 1	saving data complete : 10133 ms
> 
> simulated 100000000 photons (100000000) with 1 devices (repeat x1)
> MCX simulation speed: 9935.42 photon/ms
> total simulated energy: 0.00	absorbed:  -nan%
> (loss due to initial specular reflection is excluded in the total)

This is running on a laptop with a integrated Vega GPU. In the following days I will test in a RDNA2 dGPU. I suspect it is a bug in rusticl.

**Comment by fangq** [comment] 2023-05-23 15:24
@nicocarbone, thanks for sharing this result - I am curious if you can do this

1. disable normalization by `./run_benchmark1.sh -U 0`, and
2. print the debug output by running `./run_benchmark1.sh -n 2 -J "-DMCX_GPU_DEBUG"` 

from your log, it seems mcxcl did run (it took over 10 seconds to complete), but normalization make data nan because the normalization factor is inf. by disabling normalization, we can figure out which voxel yields inf output

the second command is what I used to debug step-by-step photon propagation. It prints every single step of the simulation, so one has to limit the photon to a few to see if they follow the desired processing path.

with these, we may have some clue how close are we to make mcxcl to be compatible with this OpenCL runtime.

**Comment by nicocarbone** [comment] 2023-05-23 15:56
Hi @fangq. Here are the requested outputs:

```
./run_benchmark1.sh -U 0
==============================================================================
=                       Monte Carlo eXtreme (MCX) -- OpenCL                  =
=          Copyright (c) 2010-2022 Qianqian Fang <q.fang at neu.edu>         =
=                             http://mcx.space/                              =
=                                                                            =
= Computational Optics&Translational Imaging (COTI) Lab - http://fanglab.org =
=   Department of Bioengineering, Northeastern University, Boston, MA, USA   =
==============================================================================
=    The MCX Project is funded by the NIH/NIGMS under grant R01-GM114365     =
==============================================================================
$Rev::4fdc45$v2022.10$Date::2018-03-29 00:35:53 -04$by $Author::Qianqian Fang$
==============================================================================
- variant name: [Detective MCXCL] compiled with OpenCL version [1]
- compiled with: [RNG] xoroshiro128+ [Seed Length] 4
initializing streams ...	init complete : 0 ms
building kernel with option: -cl-mad-enable -DMCX_USE_NATIVE -DMCX_SRC_PENCIL -DMED_TYPE=1  -DUSE_ATOMIC -DMCX_SAVE_DETECTORS  -DINTERNAL_SOURCE
build program complete : 22 ms
- [device 0(1852139309): AMD Radeon Graphics (renoir, LLVM 15.0.7, DRM 3.52, 6.3.3-060303-gen] threadph=5580 extra=6400 np=100000000 nthread=17920 nblock=64 sharedbuf=1536
set kernel arguments complete : 25 ms
lauching mcx_main_loop for time window [0.0ns 5.0ns] ...
simulation run# 1 ... 
kernel complete:  	10453 ms
retrieving flux ... 	detected 14269 photons, total: 14269	transfer complete:        10477 ms
saving data to file ... 216000 1	saving data complete : 10478 ms

simulated 100000000 photons (100000000) with 1 devices (repeat x1)
MCX simulation speed: 9589.57 photon/ms
total simulated energy: 0.00	absorbed:  -nan%
(loss due to initial specular reflection is excluded in the total)
```


```
./run_benchmark1.sh -n 2 -J "-DMCX_GPU_DEBUG"
==============================================================================
=                       Monte Carlo eXtreme (MCX) -- OpenCL                  =
=          Copyright (c) 2010-2022 Qianqian Fang <q.fang at neu.edu>         =
=                             http://mcx.space/                              =
=                                                                            =
= Computational Optics&Translational Imaging (COTI) Lab - http://fanglab.org =
=   Department of Bioengineering, Northeastern University, Boston, MA, USA   =
==============================================================================
=    The MCX Project is funded by the NIH/NIGMS under grant R01-GM114365     =
==============================================================================
$Rev::4fdc45$v2022.10$Date::2018-03-29 00:35:53 -04$by $Author::Qianqian Fang$
==============================================================================
- variant name: [Detective MCXCL] compiled with OpenCL version [1]
- compiled with: [RNG] xoroshiro128+ [Seed Length] 4
initializing streams ...	init complete : 0 ms
building kernel with option: -cl-mad-enable -DMCX_USE_NATIVE -DMCX_SRC_PENCIL -DMED_TYPE=1  -DMCX_GPU_DEBUG -DUSE_ATOMIC -DMCX_SAVE_DETECTORS  -DINTERNAL_SOURCE
build program complete : 108 ms
- [device 0(1852139309): AMD Radeon Graphics (renoir, LLVM 15.0.7, DRM 3.52, 6.3.3-060303-gen] threadph=0 extra=2 np=2 nthread=17920 nblock=64 sharedbuf=1536
set kernel arguments complete : 348 ms
lauching mcx_main_loop for time window [0.0ns 5.0ns] ...
simulation run# 1 ... 
thread workload [0.000000] done over [1]
thread workload [0.000000] done over [1]
photonid [1] L=0.000000 w=1.000000e+00 medium=1
photonid [1] L=0.000000 w=1.000000e+00 medium=1
scat L=1.008849 RNG=[6.752534e-01 9.071016e-02 3.043666e-01] 
scat L=0.633916 RNG=[2.219677e-04 1.460687e-01 4.796697e-01] 
p=[29.000000 29.000000 0.000000] -> <0.000000 0.000000 1.000000>*1.000000 -> flip=2
p=[29.000000 29.000000 0.000000] -> <0.000000 0.000000 1.000000>*0.633916 -> flip=2
update p=[29.000000 29.000000 1.000000] -> f.z=1.000000
update p=[29.000000 29.000000 0.633916] -> f.z=0.633916
idx1d [1769]->[5369]
idx1d [1769]->[1769]
medium [1]->[1]
medium [1]->[1]
field add to 1769->0.004988(1)
deposit to [1769] 9.975076e-01, w=0.995012
atomic write to [1769] 1.000000e+00, w=0.995012
photonid [1] L=0.008849 w=9.950125e-01 medium=1
photonid [1] L=0.000000 w=9.968354e-01 medium=1
scat L=1.003348 RNG=[4.834565e-01 9.165916e-01 5.156159e-03] 
scat phi=2.353462
scat theta=1.293929
new dir: -6.78316e-01 6.82034e-01 2.73344e-01
p=[29.000000 29.000000 1.000000] -> <0.000000 0.000000 1.000000>*0.008849 -> flip=2
p=[29.000000 29.000000 0.633916] -> <-0.678316 0.682034 0.273344>*0.000000 -> flip=0
update p=[29.000000 29.000000 1.008849] -> f.z=0.008849
update p=[29.000000 29.000000 0.633916] -> f.z=0.000000
idx1d [5369]->[5369]
idx1d [1769]->[1768]
medium [1]->[1]
medium [1]->[1]
field add to 1769->0.003165(1)
deposit to [1769] 6.329179e-01, w=0.996835
atomic write to [1769] 1.000000e+00, w=0.996835
photonid [1] L=0.000000 w=9.949685e-01 medium=1
photonid [1] L=1.003348 w=9.968354e-01 medium=1
scat L=0.738876 RNG=[4.922122e-01 9.191260e-01 9.816227e-01] 
scat phi=3.079135
scat theta=2.867843
new dir: -2.69816e-01 1.68741e-02 -9.62764e-01
p=[29.000000 29.000000 1.008849] -> <-0.269816 0.016874 -0.962764>*0.000000 -> flip=0
p=[29.000000 29.000000 0.633916] -> <-0.678316 0.682034 0.273344>*1.003348 -> flip=2
update p=[29.000000 29.000000 1.008848] -> f.z=0.000000
update p=[28.319412 29.684317 0.908175] -> f.z=1.003348
idx1d [5369]->[5368]
idx1d [1768]->[1768]
medium [1]->[1]
medium [1]->[1]
field add to 5369->0.000044(1)
deposit to [5369] 8.797646e-03, w=0.994968
atomic write to [5369] 9.950125e-01, w=0.994968
photonid [1] L=0.738875 w=9.949685e-01 medium=1
photonid [1] L=0.000000 w=9.918471e-01 medium=1
scat L=0.678311 RNG=[6.299847e-01 3.245438e-01 7.262471e-01] 
scat phi=1.180483
scat theta=2.439779
new dir: 4.73348e-02 -8.94264e-01 -4.45029e-01
p=[29.000000 29.000000 1.008848] -> <-0.269816 0.016874 -0.962764>*0.009191 -> flip=2
p=[28.319412 29.684317 0.908175] -> <0.047335 -0.894264 -0.445029>*0.678311 -> flip=1
update p=[28.997520 29.000154 1.000000] -> f.z=0.009191
update p=[28.351521 29.077728 0.606308] -> f.z=0.678311
idx1d [5368]->[1768]
idx1d [1768]->[1768]
medium [1]->[1]
medium [1]->[1]
field add to 5368->0.000046(1)
deposit to [5368] 9.143353e-03, w=0.994923
atomic write to [5368] 9.949685e-01, w=0.994923
photonid [1] L=0.729685 w=9.949228e-01 medium=1
photonid [1] L=0.000000 w=9.884889e-01 medium=1
scat L=1.083995 RNG=[8.094449e-01 4.220558e-01 5.654941e-01] 
scat phi=3.201379
scat theta=0.392765
new dir: 2.98804e-02 -9.97169e-01 -6.89998e-02
p=[28.997520 29.000154 1.000000] -> <-0.269816 0.016874 -0.962764>*0.729685 -> flip=2
p=[28.351521 29.077728 0.606308] -> <0.029880 -0.997169 -0.069000>*0.077949 -> flip=1
update p=[28.800640 29.012466 0.297486] -> f.z=0.729685
update p=[28.353849 29.000000 0.600929] -> f.z=0.077949
idx1d [1768]->[1768]
idx1d [1768]->[1708]
medium [1]->[1]
medium [1]->[1]
field add to 1768->0.008732(1)
deposit to [1768] 1.746356e+00, w=0.988104
atomic write to [1768] 9.968354e-01, w=0.988104
photonid [1] L=0.000000 w=9.912995e-01 medium=1
photonid [1] L=1.006046 w=9.881036e-01 medium=1
scat L=0.328314 RNG=[5.550520e-01 2.620453e-01 8.513635e-01] 
scat phi=5.657578
scat theta=1.659114
new dir: 8.36073e-01 5.32160e-01 -1.33369e-01
p=[28.800640 29.012466 0.297486] -> <0.836073 0.532160 -0.133369>*0.238448 -> flip=0
p=[28.353849 29.000000 0.600929] -> <0.029880 -0.997169 -0.069000>*1.002839 -> flip=1
update p=[29.000000 29.139359 0.265684] -> f.z=0.238448
update p=[28.383814 28.000000 0.531733] -> f.z=1.002839
idx1d [1768]->[1769]
idx1d [1708]->[1648]
medium [1]->[1]
medium [1]->[1]
field add to 1768->0.004804(1)
field add to 1708->0.004942(1)
deposit to [1768] 9.608984e-01, w=0.990118
deposit to [1708] 9.884357e-01, w=0.983161
atomic write to [1768] 9.949228e-01, w=0.990118
atomic write to [1708] 9.881036e-01, w=0.983161
photonid [1] L=0.089866 w=9.901183e-01 medium=1
photonid [1] L=0.003207 w=9.831614e-01 medium=1
p=[29.000000 29.139359 0.265684] -> <0.836073 0.532160 -0.133369>*0.089866 -> flip=0
p=[28.383814 28.000000 0.531733] -> <0.029880 -0.997169 -0.069000>*0.003207 -> flip=1
update p=[29.075134 29.187181 0.253699] -> f.z=0.089866
update p=[28.383909 27.996801 0.531512] -> f.z=0.003207
idx1d [1769]->[1769]
idx1d [1648]->[1648]
medium [1]->[1]
medium [1]->[1]
photonid [1] L=0.000000 w=9.896734e-01 medium=1
photonid [1] L=0.000000 w=9.831457e-01 medium=1
scat L=0.865109 RNG=[3.311299e-01 9.752357e-02 9.886699e-01] 
scat L=0.655813 RNG=[7.437229e-03 5.777659e-01 3.488793e-01] 
scat phi=5.347580
scat phi=5.971707
scat theta=1.284988
scat theta=1.804457
new dir: 5.86362e-01 -5.42257e-01 -6.01778e-01
new dir: -3.06836e-01 2.85821e-01 -9.07831e-01
p=[29.075134 29.187181 0.253699] -> <0.586362 -0.542257 -0.601778>*0.345190 -> flip=1
p=[28.383909 27.996801 0.531512] -> <-0.306836 0.285821 -0.907831>*0.011191 -> flip=1
update p=[29.277540 29.000000 0.045971] -> f.z=0.345190
update p=[28.380476 28.000000 0.521352] -> f.z=0.011191
idx1d [1769]->[1709]
idx1d [1648]->[1708]
medium [1]->[1]
medium [1]->[1]
field add to 1769->0.002151(1)
field add to 1648->0.000071(1)
deposit to [1769] 4.302979e-01, w=0.987967
deposit to [1648] 1.415014e-02, w=0.983091
atomic write to [1769] 9.901183e-01, w=0.987967
atomic write to [1648] 9.831614e-01, w=0.983091
photonid [1] L=0.519919 w=9.879668e-01 medium=1
photonid [1] L=0.644621 w=9.830907e-01 medium=1
p=[29.277540 29.000000 0.045971] -> <0.586362 -0.542257 -0.601778>*0.076392 -> flip=2
p=[28.380476 28.000000 0.521352] -> <-0.306836 0.285821 -0.907831>*0.574283 -> flip=2
update p=[29.322334 28.958576 -0.000000] -> f.z=0.076392
update p=[28.204266 28.164143 -0.000000] -> f.z=0.574283
idx1d [1709]->[-1891]
idx1d [1708]->[-1892]
moving outside: [29.322334 28.958576 -0.000000], idx1d [-1]->[out], bcflag 0
moving outside: [28.204266 28.164143 -0.000000], idx1d [-1]->[out], bcflag 0
medium [1]->[0]
medium [1]->[0]
field add to 1709->0.000377(1)
field add to 1708->0.002819(1)
deposit to [1709] 7.545948e-02, w=0.987589
deposit to [1708] 5.637646e-01, w=0.980272
atomic write to [1709] 9.879668e-01, w=0.987589
atomic write to [1708] 9.830907e-01, w=0.980272
direct relaunch at idx=[-1] mediaid=[0] bc=[0] ref=[0]
direct relaunch at idx=[-1] mediaid=[0] bc=[0] ref=[0]
thread workload [1.000000] done over [1]
thread workload [1.000000] done over [1]
kernel complete:  	350 ms
retrieving flux ... 	detected 0 photons, total: 0	transfer complete:        372 ms
normalizing raw data ...	source 1, normalization factor alpha=100000000.000000
saving data to file ... 216000 1	saving data complete : 375 ms

simulated 2 photons (2) with 1 devices (repeat x1)
MCX simulation speed: 1.00 photon/ms
total simulated energy: 2.00	absorbed: 1.60693%
(loss due to initial specular reflection is excluded in the total)
```

It seems like all photons are detected and none are absorbed, which I assume is not correct.

**Comment by fangq** [comment] 2023-05-23 20:30
@nicocarbone, actually, the results look fine to me. I suspect that the issue is local (meaning that perhaps one of the specific operations for a particular photon or a specific voxel that yields undesired values - such as nan or inf).

can you run
```
./run_benchmark1.sh -U 0 -F jnii
```
and send me the output .jnii file somewhere (such as a dropbox or google drive)? I can take a look. Also, is there an deb rusticl installer for Ubuntu? I'd be happy to install it on my system and figure out what was the issue.

**Comment by nicocarbone** [comment] 2023-05-23 20:51
@fangq I uploaded the results from the run here: [Drive](https://drive.google.com/file/d/1nwUp7D7nzwpfOTMXZpD2usesopqM7LhZ/view?usp=sharing)

I am using this [ppa](https://launchpad.net/~ernstp/+archive/ubuntu/mesarc) to install a updated mesa with rusticl on Ubuntu 23.04.

And here are the results of the test:

```
 ./testmcx.sh
test binary file ... 
ok
test libraries ... 
ok
test execution permission ... 
ok
test version number ... 
ok
test help info ... 
ok
test gpu info ... 
fail to print GPU
test built-in benchmark listing ... 
ok
test exporting json input from builtin examples ... 
ok
test exporting json input from builtin examples with volume data ... 
ok
test default options ... 
ok
test exporting builtin volume with gzip compression ... 
ok
test json input modifier --json ... 
ok
test homogeneous domain simulation ... 
fail to run cube60 benchmark
test boundary reflection ... 
fail to run cube60b benchmark
test boundary reflection flag -b ... 
fail to use -b 1 flag to enable reflection
test boundary condition flag -B ... 
fail to use -B flag to set facet based boundary condition
test cyclic boundary condition ... 
fail to apply the cylic boundary condition
test photon detection ... 
fail to detect photons in the cube60b benchmark
test planary widefield source ... 
fail to run cube60planar benchmark
test isotropic source ... 
fail to run isotropic source
test cone beam source ... 
fail to run cone beam source
test Fourier source ... 
fail to run Fourier source
test pencil array source ... 
fail to run pencil array source
test boundary detector flags ... 
fail to detect photons in the cube60b benchmark
test saving photon seeds ... 
fail to save photon seeds
test photon replay flag -E ... 
fail to run photon replay -E
test photon replay ... 
fail to run photon replay
test heterogeneous domain ... 
fail to run spherebox benchmark
test save detect photon data flag -w ... 
fail to save detected photon data using -w flag
test progress bar -D P ... 
fail to print progress bar
test saving trajectory feature -D M ... 
fail to save trajectory data via -D M
failed 20 tests
```
